apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: valvechain-api-hpa
  namespace: valvechain
  labels:
    app: valvechain-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: valvechain-api
  minReplicas: 1
  maxReplicas: 10
  metrics:
  # CPU-based scaling
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  # Memory-based scaling
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  # Custom metrics for RPS (requires custom metrics API)
  - type: Pods
    pods:
      metric:
        name: requests_per_second
      target:
        type: AverageValue
        averageValue: "100"
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
      - type: Pods
        value: 2
        periodSeconds: 60
      selectPolicy: Min
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 60
      - type: Pods
        value: 4
        periodSeconds: 60
      selectPolicy: Max

---
apiVersion: autoscaling/v2
kind: VerticalPodAutoscaler
metadata:
  name: valvechain-api-vpa
  namespace: valvechain
  labels:
    app: valvechain-api
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: valvechain-api
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
    - containerName: valvechain-api
      minAllowed:
        cpu: 100m
        memory: 128Mi
      maxAllowed:
        cpu: 2
        memory: 2Gi
      controlledResources: ["cpu", "memory"]

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: valvechain-api-pdb
  namespace: valvechain
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: valvechain-api