apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: valvechain-data-pvc
  namespace: valvechain
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: fast-ssd